# Generated by Django 6.0.5 on 2026-05-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nom',
            field=models.CharField(blank=True, help_text="Nom complet de l'utilisateur", max_length=100),
        ),
        migrations.AddField(
            model_name='profil',
            name='prenom',
            field=models.CharField(blank=True, help_text="Prénom de l'utilisateur", max_length=100),
        ),
    ]
