# Generated by Django 6.0.5 on 2026-05-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_profil_nom_profil_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='onboarding_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nom',
            field=models.CharField(help_text="Nom complet de l'utilisateur", max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='prenom',
            field=models.CharField(help_text="Prénom de l'utilisateur", max_length=100),
        ),
    ]
