# Generated by Django 6.0.5 on 2026-05-26 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_experience_date_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('minimal', 'Minimaliste'), ('modern', 'Moderne'), ('future', 'Futuriste')], default='minimal', max_length=20)),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('show_profile', models.BooleanField(default=True)),
                ('show_diplomes', models.BooleanField(default=True)),
                ('show_experiences', models.BooleanField(default=True)),
                ('show_competences', models.BooleanField(default=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='cv.cv')),
            ],
        ),
    ]
