# Generated by Django 6.0.5 on 2026-05-26 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_profil_nom_profil_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie de compétence',
                'verbose_name_plural': 'Catégories de compétences',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la compétence')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='cv.categoriecompetence', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Développeur Fullstack / Technicien Supérieur en Génie Logiciel', max_length=200, verbose_name='Titre du CV')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='Accroche / Objectif professionnel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('competences', models.ManyToManyField(blank=True, related_name='cvs', to='cv.competence')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='comptes.profil')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV',
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du diplôme')),
                ('etablissement', models.CharField(max_length=200, verbose_name="Établissement d'obtention")),
                ('niveau', models.CharField(choices=[('BAC', 'Baccalauréat'), ('BAC+2', 'DTS, BTS, DUT'), ('BAC+3', 'DTSS, Licence, Licence Pro, BUT'), ('BAC+5', "Master, Diplôme d'Ingénieur"), ('BAC+8', 'Doctorat'), ('Autre', 'Autre niveau de diplôme')], max_length=10, verbose_name='Niveau du diplôme')),
                ('specialite', models.CharField(blank=True, max_length=200, verbose_name='Spécialité / Option')),
                ('annee_debut', models.PositiveIntegerField(verbose_name="Année de début d'études")),
                ('annee_obtention', models.PositiveIntegerField(blank=True, null=True, verbose_name="Année d'obtention du diplôme (ou prévue)")),
                ('en_cours', models.BooleanField(default=False, verbose_name="En cours d'obtention")),
                ('description', models.TextField(blank=True, verbose_name='Description ou projets marquants liés à ce diplôme')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='cv.cv')),
            ],
            options={
                'verbose_name': 'Diplôme',
                'verbose_name_plural': 'Diplômes',
                'ordering': ['-annee_obtention', '-annee_debut'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200, verbose_name='Intitulé du poste')),
                ('entreprise', models.CharField(max_length=200, verbose_name='Entreprise / Organisation')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('ALTER', 'Alternance'), ('FREELANCE', 'Freelance / Indépendant'), ('INTERIM', 'Intérim')], default='CDI', max_length=15, verbose_name='Type de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('poste_actuel', models.BooleanField(default=False, verbose_name="J'occupe actuellement ce poste")),
                ('description', models.TextField(blank=True, help_text='Détaillez vos tâches principales et vos résultats.', null=True, verbose_name='Missions et réalisations')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cv.cv')),
            ],
            options={
                'verbose_name': 'Expérience Professionnelle',
                'verbose_name_plural': 'Expériences Professionnelles',
                'ordering': ['-poste_actuel', '-date_debut'],
            },
        ),
    ]
