# Generated by Django 6.0.5 on 2026-05-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_debut',
            field=models.DateField(blank=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='entreprise',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entreprise / Organisation'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='poste',
            field=models.CharField(blank=True, max_length=200, verbose_name='Intitulé du poste'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='poste_actuel',
            field=models.BooleanField(blank=True, default=False, verbose_name="J'occupe actuellement ce poste"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('ALTER', 'Alternance'), ('FREELANCE', 'Freelance / Indépendant'), ('INTERIM', 'Intérim')], max_length=15, verbose_name='Type de contrat'),
        ),
    ]
